from typing import Any

from rule_builder.options import OptionFilter
from rule_builder.rules import Rule, True_, Has

from . import BVFUBJOptions as bey_opt
from .Constants.Names import item_names as itemname, location_names as locname

ProgEpisode: Rule[Any] = (True_() & OptionFilter(bey_opt.RandomEpisodes, 0))
RandEpisode: Rule[Any] = (True_() & OptionFilter(bey_opt.RandomEpisodes, 1))
Episode1Acc: Rule[Any] = (ProgEpisode & Has(itemname.PROGRESSIVE_EPISODE_UNLOCK)
                          | RandEpisode & Has(itemname.E1_UNLOCK))
Episode2Acc: Rule[Any] = (ProgEpisode & Has(itemname.PROGRESSIVE_EPISODE_UNLOCK, 2)
                          | RandEpisode & Has(itemname.E2_UNLOCK))
Episode3Acc: Rule[Any] = (ProgEpisode & Has(itemname.PROGRESSIVE_EPISODE_UNLOCK, 2)
                         | RandEpisode & Has(itemname.E3_UNLOCK))
Episode4Acc: Rule[Any] = (ProgEpisode & Has(itemname.PROGRESSIVE_EPISODE_UNLOCK, 2)
                         | RandEpisode & Has(itemname.E4_UNLOCK))
Episode5Acc: Rule[Any] = (ProgEpisode & Has(itemname.PROGRESSIVE_EPISODE_UNLOCK, 2)
                         | RandEpisode & Has(itemname.E5_UNLOCK))
Episode6Acc: Rule[Any] = (ProgEpisode & Has(itemname.PROGRESSIVE_EPISODE_UNLOCK, 2)
                         | RandEpisode & Has(itemname.E6_UNLOCK))
Episode7Acc: Rule[Any] = (ProgEpisode & Has(itemname.PROGRESSIVE_EPISODE_UNLOCK, 2)
                          | RandEpisode & Has(itemname.E7_UNLOCK))

OpenRounds: Rule[Any] = True_() & OptionFilter(bey_opt.RoundShuffle, 0)
ProgRound: Rule[Any] = True_() & OptionFilter(bey_opt.RoundShuffle, 1)
RandRound: Rule[Any] = (True_() & OptionFilter(bey_opt.RoundShuffle, 2))
Episode1Round1Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                          | RandRound & Has(itemname.E1R1_UNLOCK))
Episode1Round2Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E1R2_UNLOCK))
Episode1Round3Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E1R3_UNLOCK))
Episode1Round4Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E1R4_UNLOCK))
Episode1Round5Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E1R5_UNLOCK))
Episode1Round6Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E1R6_UNLOCK))
Episode1Round7Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                          | RandRound & Has(itemname.E1R7_UNLOCK))
Episode1RoundBAcc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                          | RandRound & Has(itemname.E1RB_UNLOCK))
Episode2Round1Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E2R1_UNLOCK))
Episode2Round2Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E2R2_UNLOCK))
Episode2Round3Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E2R3_UNLOCK))
Episode2Round4Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E2R4_UNLOCK))
Episode2Round5Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E2R5_UNLOCK))
Episode2Round6Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E2R6_UNLOCK))
Episode2Round7Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E2R7_UNLOCK))
Episode2RoundBAcc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                          | RandRound & Has(itemname.E2RB_UNLOCK))
Episode3Round1Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E3R1_UNLOCK))
Episode3Round2Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E3R2_UNLOCK))
Episode3Round3Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E3R3_UNLOCK))
Episode3Round4Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E3R4_UNLOCK))
Episode3Round5Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E3R5_UNLOCK))
Episode3Round6Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E3R6_UNLOCK))
Episode3Round7Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E3R7_UNLOCK))
Episode3RoundBAcc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                          | RandRound & Has(itemname.E3RB_UNLOCK))
Episode4Round1Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E4R1_UNLOCK))
Episode4Round2Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E4R2_UNLOCK))
Episode4Round3Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E4R3_UNLOCK))
Episode4Round4Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E4R4_UNLOCK))
Episode4Round5Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E4R5_UNLOCK))
Episode4Round6Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E4R6_UNLOCK))
Episode4Round7Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E4R7_UNLOCK))
Episode4RoundBAcc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                          | RandRound & Has(itemname.E4RB_UNLOCK))
Episode5Round1Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E5R1_UNLOCK))
Episode5Round2Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E5R2_UNLOCK))
Episode5Round3Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E5R3_UNLOCK))
Episode5Round4Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E5R4_UNLOCK))
Episode5Round5Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E5R5_UNLOCK))
Episode5Round6Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E5R6_UNLOCK))
Episode5Round7Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E5R7_UNLOCK))
Episode5RoundBAcc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                          | RandRound & Has(itemname.E5RB_UNLOCK))
Episode6Round1Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E6R1_UNLOCK))
Episode6Round2Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E6R2_UNLOCK))
Episode6Round3Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E6R3_UNLOCK))
Episode6Round4Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E6R4_UNLOCK))
Episode6Round5Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E6R5_UNLOCK))
Episode6Round6Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E6R6_UNLOCK))
Episode6Round7Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E6R7_UNLOCK))
Episode6RoundBAcc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                          | RandRound & Has(itemname.E6RB_UNLOCK))
Episode7Round1Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E7R1_UNLOCK))
Episode7Round2Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E7R2_UNLOCK))
Episode7Round3Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E7R3_UNLOCK))
Episode7Round4Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E7R4_UNLOCK))
Episode7Round5Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E7R5_UNLOCK))
Episode7Round6Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                        | RandRound & Has(itemname.E7R6_UNLOCK))
Episode7Round7Acc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                         | RandRound & Has(itemname.E7R7_UNLOCK))
Episode7RoundBAcc: Rule[Any] = (ProgRound & Has(itemname.PROGRESSIVE_ROUND_UNLOCK)
                          | RandRound & Has(itemname.E7RB_UNLOCK))
ParChecks: Rule[Any] = True_() & OptionFilter(bey_opt.ParChecks, 0) ##todo

MoveRandoOff: Rule[Any] = True_() & OptionFilter(bey_opt.ShuffleMoves, 0)
CanBoost: Rule[Any] = MoveRandoOff | OptionFilter(bey_opt.ShuffleMoves, 1) & Has(itemname.BOOST_UPGRADE)